server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /uploadfile/ {
        proxy_pass http://backend:8000/uploadfile/;
    }

    location /ask {
        proxy_pass http://backend:8000/ask;
    }
}